# Generated by Django 3.1.2 on 2020-11-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoltel_site', '0003_auto_20201123_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 18, 24, 10, 275723)),
        ),
    ]
