# Generated by Django 3.1.2 on 2020-11-25 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revoltel_site', '0004_auto_20201124_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
